---
- hosts: dockermaster
  gather_facts: no
  tasks:
  - name: Copying war file
    copy:
      src: /DevOps/ansible/ILP_Bookstore.war
      dest: /DevOps/ansible/
  - name: Copying dockerfile. 
    copy:
      src: $WORKSPACE/Dockerfile
      dest: /DevOps/ansible/
  - name: Remove Image
    docker_image:
      state: absent
      name: bookstoreimg
      tag: v1
      force: yes
  - name: creating docker image
    docker_image:
      path: /DevOps/ansible/
      name: bookstoreimg
      tag: v1
      pull: no
      state: build
  - name: deleting existing service
    shell: "docker service rm capstoneservice2"
    ignore_errors: True
  - name: creating docker service
    shell: "docker service create --name capstoneservice2 --replicas 2 -p 22021:8080 bookstoreimg:v1"
